"""add streams and zones

Revision ID: f22731edb9d3
Revises: 90e49764a403
Create Date: 2026-03-19 00:09:07.461656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f22731edb9d3'
down_revision: Union[str, Sequence[str], None] = '90e49764a403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('streams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.drop_table('strava_activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_activities',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('moving_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('elapsed_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('strava_activities_pkey'))
    )
    op.drop_table('activities', schema='raw')
    # ### end Alembic commands ###
